# Generated by Django 4.2.3 on 2024-01-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0007_alter_client_id_alter_exchangedtoken_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonce',
            name='next_path',
            field=models.TextField(null=True),
        ),
    ]
